tarot24/portal/urls.py
from django.urls import path
from .views import PostsList, PostDetail, PostCreate, PostUpdate, PostDelete, category_list, subscribe

# http://:127.0.0.1:8000/post/

urlpatterns = [
    path('', PostsList.as_view(), name='post_list'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('article/create/', PostCreate.as_view(), name='article_create'),
    path('article/<int:pk>/update/', PostUpdate.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', PostDelete.as_view(), name='article_delete'),

    path('cart/create/', PostCreate.as_view(), name='cart_create'),
    path('cart/<int:pk>/update/', PostUpdate.as_view(), name='cart_update'),
    path('cart/<int:pk>/delete/', PostDelete.as_view(), name='cart_delete'),
    path('category_list/', category_list, name='category_list'),
    path('subscribe/<int:pk>/', subscribe, name='subscribe'),
]

tarot24/tarot24/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('post/', include('portal.urls')),
    path('sign_up/', include('sign_up.urls')),
    path('', include('protect.urls')),
    path('accounts/', include('allauth.urls')),
]

tarot24/portal/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

    def update_rating(self):
        posts_rating_sum = Post.objects.filter(author=self).aggregate(Sum('rating'))['rating__sum'] or 0
        comments_rating_sum = Comment.objects.filter(author=self).aggreate(Sum('rating'))['rating__sum'] or 0
        comments_posts_rating_sum = Comment.objects.filter(post__author=self).aggreate(Sum('rating'))[
                                        'rating__sum'] or 0

        self.rating = posts_rating_sum * 3 * comments_rating_sum
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=34, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories', blank=True)

    def __str__(self):   return self.name


class Post(models.Model):
    article = 'AR'
    cart_of_the_day = 'CD'  # аналог новости

    TYPE_CHOICES = ((article, 'статья'), (cart_of_the_day, 'карта дня'))

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post_type = models.CharField(max_length=2, choices=TYPE_CHOICES, default=cart_of_the_day)
    time_publication = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=67)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        if len(self.text) > 124:
            return self.text[:124] + "..."
        return self.text


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date_time = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

tarot24/portal/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post

class PostForm(forms.ModelForm):
   class Meta:
       model = Post
       fields = [
           'author',
           'title',
           'text',
           'category'
       ]

   def clean(self):
       cleaned_data = super().clean()
       text = cleaned_data.get("text")
       if text is not None and len(text) < 100:
           raise ValidationError({
               "text": "не может быть менее 100 символов."
           })

       return cleaned_data

tarot24/portal/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import TemplateView
from .models import Post, Category
from .forms import PostForm
from .filters import PostFilter

class PostsList(ListView):
    model = Post
    ordering = '-time_publication'
    template_name = 'portal/post_list.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'portal/post_detail.html'
    context_object_name = 'post'


class PostCreate(PermissionRequiredMixin, CreateView):
    form_class = PostForm
    model = Post
    template_name = 'portal/post_edit.html'
    permission_required = ('portal.add_post',)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_message'] = 'Добавить карту дня' if 'cart' in self.request.path else 'Добавить статью'
        return context

    def form_valid(self, form):
        post = form.save(commit=False)
        if 'article' in self.request.path:
            post.post_type = 'AR'
            post.save()
        return super().form_valid(form)


class PostUpdate(LoginRequiredMixin, UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'portal/post_edit.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_message'] = 'Изменить карту дня' if 'cart' in self.request.path else 'Изменить статью'
        return context

class PostDelete(DeleteView):
    model = Post
    template_name = 'portal/post_delete.html'
    success_url = reverse_lazy('post_list')

class ProtectedView(LoginRequiredMixin, TemplateView):
    template_name = 'portal/post_edit.html'


def category_list(request):
    categories = Category.objects.all()
    return render(request, 'category_list.html', {'categories': categories})

@login_required
def subscribe(request, pk):
    category = Category.objects.get(pk=pk)
    category.subscribers.add(request.user)
    return redirect(request.META.get('HTTP_REFERER'))

tarot24/templates/portal/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

tarot24/templates/portal/post_detail.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}Пост: "{{ post.title }}"{% endblock title %}


{% block content %}
<table>
    <tr>
        <td>Автор</td>
        <td>Дата публикации</td>
        <td>Заголовок</td>
        <td>Содержание</td>
    </tr>
    <tr>
        <td>{{ post.author.user.username }}</td>
        <td>{{ post.time_publication|date:"d E Y" }}</td>
        <td>{{ post.title }}</td>
        <td>{{ post.text|censor }}</td>
    </tr>
</table>
{% endblock content %}

tarot24/templates/portal/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1> {{ title_message}}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% endblock content %}

tarot24/templates/portal/post_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}Все публикации{% endblock title %}


{% block content %}
    <h1>Все посты</h1>

       <form action="" method="get" cla
             ss="filter-form">
           {{ filterset.form.as_p }}
           {# Добавим кнопку отправки данных формы #}
           <input type="submit" value="Найти" />
       </form>

       <hr>
       {% if posts %}
<table>
    <tr>
        <td>Автор</td>
        <td>Дата публикации</td>
        <td>Заголовок</td>
        <td>Содержание</td>
        <td>Тип</td>
        <td>Действие</td>
    </tr>
    {% for post in posts %}
    <tr>
        <td>{{ post.author.user.username }}</td>
        <td>{{ post.time_publication|date:"d E Y" }}</td>
        <td><a href="{% url 'post_detail' post.id %}">{{ post.title }}</a></td>
        <td>{{ post.text|truncatewords:14 }}</td>
        <td>{{ post.get_post_type_display }}</td>
        {% if post.post_type == 'AR' %}
        <td><a href="{% url 'article_update' post.id %}">Редактировать</a><td>
        {% else %}
        <td><a href="{% url 'cart_update' post.id %}">Редактировать</a><td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% endif %}

{% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}